version : '3'
services: 
    web:
      container_name: "node-server"
      ports: 
       - "8083:8083"
      build: .
      links:
       - redis
    redis: 
      image: redis 
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - "redis-data:/data"
volumes:
  redis-data:
   driver: local 
     